name: Verify Zip Contents

on:
  pull_request:
    paths:
      - '*.zip' # Specify the pattern for zip files

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unzip the archive
        run: unzip '*.zip' -d extracted

      - name: Check for install.sh
        run: |
          if [ -f extracted/GC/install.sh ]; then
            echo "install.sh found in the zip."
          else
            echo "Error: install.sh not found in the zip, are we sure this is the linux agent binary?."
            exit 1 # Fail the workflow if install.sh is missing
          fi
